name: Docs

on:
  push:
    branches: [ main ]

 ## Delete below when merged to main!
 ## Added such that one can test pages deployment on branch before merging
  pull_request:
    branches: [ main ] 

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'adopt'

      - name: Build documentation
        run: |
          chmod +x ./gradlew
          ./gradlew GithubApi:dokkaHtml

      - name: Publish documentation
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          BRANCH: gh-pages
          FOLDER: GithubApi/docs/dokkaHtml
